spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/cities_db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
    username: <username>
    password: <password>
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  main:
    banner-mode: "off"

logging:
  level:
    org:
      springframework: ERROR